version: "3.8"

services:
    exams:
        build: .
        container_name: exams 
        networks:
         - backend
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html/exam
    mysql_exam:
        image: mysql:5.6
        container_name: mysql_exam
        networks:
            - backend
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=activelamp_exam
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./db2:/var/lib/mysql
    mailhog:
        image: mailhog/mailhog:v1.0.0
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - backend
    phpmyadmin:
        build: ./docker/phpmyadmin
        ports:
            - "8080:80"
        networks:
            - backend
        environment:
            - "PMA_HOST=mysql_exam"
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_PASSWORD=root"

networks:
    backend:
